// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        google()
        mavenCentral()
        jcenter()

        maven { url 'https://artifacts.applovin.com/android' }
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.2.1'
        classpath 'com.google.gms:google-services:4.3.15'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.2.0'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()

        // Required for PRDownloader 1.0.1
        maven { url 'https://maven.scijava.org/content/repositories/public/' }

        maven { url 'https://jitpack.io' }
        maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }

        maven { url 'https://artifacts.applovin.com/android' }

        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
